<center>
<h2>CALDEN CONSULTORIA - Leitura Dados FME e Mapas
</h2>
<h3>Projeto: Invetario de Campo</h3>
</center>
</left>
<h3>Cliente: Light</h3>
<h4>Notebook 01: Leitura

In [3]:
import pandas as pd
import geopandas as gpd

In [4]:

def ler_area_de_risco(pasta_ARisco):
    shp_AR0 = gpd.read_file(pasta_ARisco + 'ACAC.json')
    shp_AR1 = gpd.read_file(pasta_ARisco + 'ASRO.geojson')
    shp_AR2 = gpd.read_file(pasta_ARisco + 'COMUNIDADES_DOMINADAS_PELA_MILICIA.geojson')
    shp_AR3 = gpd.read_file(pasta_ARisco + 'COMUNIDADES_DOMINADAS_PELO_AMIGOS_DOS_AMIGOS.geojson')
    shp_AR4 = gpd.read_file(pasta_ARisco + 'COMUNIDADES_DOMINADAS_PELO_COMANDO_VEMELHO.geojson')
    shp_AR5 = gpd.read_file(pasta_ARisco + 'COMUNIDADES_DOMINADAS_PELO_TERCEIRO_COMANDO_PURO.geojson')

    shp_AR0 = shp_AR0[shp_AR0['geometry'].geom_type == 'Polygon']
    shp_AR1 = shp_AR1[shp_AR1['geometry'].geom_type == 'Polygon']
    shp_AR2 = shp_AR2[shp_AR2['geometry'].geom_type == 'Polygon']
    shp_AR3 = shp_AR3[shp_AR3['geometry'].geom_type == 'Polygon']
    shp_AR4 = shp_AR4[shp_AR4['geometry'].geom_type == 'Polygon']
    shp_AR5 = shp_AR5[shp_AR5['geometry'].geom_type == 'Polygon']

    shp_AR0 = shp_AR0.to_crs('EPSG:4674')
    shp_AR1 = shp_AR1.to_crs('EPSG:4674')
    shp_AR2 = shp_AR2.to_crs('EPSG:4674')
    shp_AR3 = shp_AR3.to_crs('EPSG:4674')
    shp_AR4 = shp_AR4.to_crs('EPSG:4674')
    shp_AR5 = shp_AR5.to_crs('EPSG:4674')

    return shp_AR0, shp_AR1, shp_AR2, shp_AR3, shp_AR4, shp_AR5

# PAth

In [5]:
path_ext = "D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/6. FME/"

In [6]:
extracao = "01_13.12.2023_Extracao"

In [7]:
path_escopo = "D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/0. Escopo/"

In [8]:
escopo = "ALIM VALIDADOS - 12.12.2023.xlsx"

In [9]:
path_resultados = "D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/3. Execução/3. Streamlit/2. Resultados/"

In [12]:
pasta_ARisco = 'D:/GIT/2023_Light_Dash/1 - Poligonais áreas de risco/'

In [13]:
resultados = ler_area_de_risco(pasta_ARisco)
shp_AR0, shp_AR1, shp_AR2, shp_AR3, shp_AR4, shp_AR5 = resultados

In [14]:
shp_AR0

,name,open,styleUrl,fill-opacity,fill,stroke-opacity,stroke,stroke-width,icon-scale,icon-offset-units,icon,geometry
0,ALEMÃO,NaN,#msn_ylw-pushpin7,0.85098,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.26797 -22.86233, -43.26784 -22.8..."
1,ANDARAÍ,NaN,#msn_ylw-pushpin11,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.25597 -22.93142, -43.25670 -22.9..."
2,BATAN,NaN,#msn_ylw-pushpin7,0.85098,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.44837 -22.85567, -43.44717 -22.8..."
3,BELFORD ROXO 1 e 2,NaN,#msn_ylw-pushpin18,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.34254 -22.71284, -43.34142 -22.7..."
4,BELFORD ROXO 1 e 2,NaN,#msn_ylw-pushpin40,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.33016 -22.71706, -43.33598 -22.7..."
5,BOREL,NaN,#msn_ylw-pushpin41,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.25270 -22.93977, -43.25205 -22.9..."
6,CABRITOS/TABAJARA,NaN,#msn_ylw-pushpin01,0.85098,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.19233 -22.96294, -43.19175 -22.9..."
7,CAXIAS 1,NaN,#msn_ylw-pushpin40,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.31890 -22.71004, -43.31690 -22.7..."
8,CAXIAS 2,NaN,#msn_ylw-pushpin40,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.32309 -22.71351, -43.32506 -22.7..."
9,CAXIAS 3,NaN,#msn_ylw-pushpin100,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.30393 -22.75144, -43.30086 -22.7..."
10,CAXIAS 4,NaN,#msn_ylw-pushpin100,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.28635 -22.76977, -43.29013 -22.7..."
11,CAXIAS 5,NaN,#msn_ylw-pushpin00,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.33508 -22.75765, -43.33732 -22.7..."
12,CHAPEU MANGUEIRA BABILONIA,NaN,#msn_ylw-pushpin6,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.17034 -22.96115, -43.17040 -22.9..."
13,CIDADE DE DEUS,NaN,#msn_ylw-pushpin20,0.85098,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.35538 -22.95336, -43.35415 -22.9..."
14,COELHO DA ROCHA,NaN,#msn_ylw-pushpin90,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.38028 -22.78489, -43.37755 -22.7..."
15,CORDOVIL,NaN,#msn_ylw-pushpin8,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.30499 -22.81639, -43.30799 -22.8..."
16,COSMOS 1,NaN,#msn_ylw-pushpin90,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.61682 -22.87806, -43.61866 -22.8..."
17,COSMOS 2,NaN,#msn_ylw-pushpin90,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.59460 -22.88448, -43.59287 -22.8..."
18,CURICICA,NaN,#msn_ylw-pushpin30,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.38069 -22.93728, -43.38252 -22.9..."
19,ÉDEN,NaN,#msn_ylw-pushpin30,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.39703 -22.77774, -43.40229 -22.7..."
20,FORMIGA,NaN,#msn_ylw-pushpin001,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.24532 -22.93943, -43.24490 -22.9..."
21,MACACOS,NaN,#msn_ylw-pushpin11,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.25831 -22.91574, -43.25635 -22.9..."
22,MESQUITA,NaN,#msn_ylw-pushpin30,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.42258 -22.79646, -43.42499 -22.7..."
23,MONTE LÍBANO,NaN,#msn_ylw-pushpin2,0.74902,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.41613 -22.76490, -43.41504 -22.7..."
24,NILOPOLIS,NaN,#msn_ylw-pushpin30,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.39067 -22.81402, -43.39689 -22.8..."
25,NILOPOLIS CONVENCIONAL,NaN,#msn_ylw-pushpin,0.00000,NaN,NaN,NaN,3.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.42098 -22.79883, -43.42152 -22.7..."
26,NOVA IGUAÇU I,NaN,#msn_ylw-pushpin02,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.51448 -22.77295, -43.51509 -22.7..."
27,NOVA IGUAÇU II,NaN,#msn_ylw-pushpin30,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.50682 -22.75455, -43.49995 -22.7..."
28,NOVA IGUAÇU III,NaN,#msn_ylw-pushpin02,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.53527 -22.76258, -43.53730 -22.7..."
29,REALENGO 1,NaN,#msn_ylw-pushpin04,0.00000,NaN,NaN,NaN,4.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.41984 -22.88228, -43.42319 -22.8..."
30,REALENGO 2,NaN,#m_ylw-pushpin,0.00000,NaN,1.0,#aa0000,4.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.42212 -22.87986, -43.41899 -22.8..."
31,RICARDO DE ALBUQUERQUE,1,#msn_ylw-pushpin_copy810,0.00000,NaN,NaN,NaN,3.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.41480 -22.82142, -43.41577 -22.8..."
32,RIO DAS PEDRAS 1,1,#msn_ylw-pushpin0,0.00000,#aa0000,1.0,#aa0000,3.5,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.33889 -22.97595, -43.34261 -22.9..."
33,RIO DAS PEDRAS 2,NaN,#msn_ylw-pushpin0,0.00000,#aa0000,1.0,#aa0000,3.5,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.33400 -22.97766, -43.33090 -22.9..."
34,ROSALI I,NaN,#msn_ylw-pushpin3,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.38792 -22.80169, -43.38573 -22.8..."
35,ROSALI II,NaN,#msn_ylw-pushpin3,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.37366 -22.79345, -43.37315 -22.7..."
36,SALGUEIRO,NaN,#msn_ylw-pushpin310,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.22882 -22.92938, -43.22973 -22.9..."
37,SANTA MARTA,NaN,#msn_ylw-pushpin03,0.80000,#ffdb26,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.19380 -22.94983, -43.19254 -22.9..."
38,SEPETIBA,NaN,#msn_ylw-pushpin50,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.69577 -22.95947, -43.70373 -22.9..."
39,TOMAZINHO,NaN,#msn_ylw-pushpin12,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.41011 -22.79145, -43.40542 -22.7..."
40,VIGÁRIO GERAL,NaN,#msn_blu-blank,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/paddle/blu...,"POLYGON ((-43.32371 -22.80976, -43.31747 -22.8..."
41,VILAR DOS TELES I,NaN,#msn_ylw-pushpin4,0.80000,#ff0000,NaN,NaN,2.0,1.1,"[pixels, pixels]",http://maps.google.com/mapfiles/kml/pushpin/yl...,"POLYGON ((-43.36454 -22.76259, -43.34502 -22.7..."

In [15]:
shp_AR0.to_pickle(path_resultados + "shp_AR0.pkl")
shp_AR1.to_pickle(path_resultados + "shp_AR1.pkl")
shp_AR2.to_pickle(path_resultados + "shp_AR2.pkl")
shp_AR3.to_pickle(path_resultados + "shp_AR3.pkl") 
shp_AR4.to_pickle(path_resultados + "shp_AR4.pkl") 
shp_AR5.to_pickle(path_resultados + "shp_AR5.pkl")

# Leitura escopo

In [9]:
alimentadores_validados = pd.read_excel('ALIM VALIDADOS - 12.12.2023.xlsx')

# Leitura trechos

In [10]:
path_ext = "Extracao/6 - Extrações FME (1)/"

In [11]:
gdf_trecho_mt = gpd.read_file(path_ext + "TRECHO_MT.shp")
gdf_trecho_mt['geometry'] = gdf_trecho_mt['geometry'].to_crs(4326)

In [12]:
gdf_trecho_mt = gdf_trecho_mt.set_geometry('geometry')

In [13]:
gdf_trecho_mt.columns

Index(['CODIGO', 'COMPRIMENT', 'COMPRIME00', 'FASES', 'TIPO_INSTA',
       'TENSAO_OPE', 'PROPRIETAR', 'MAX_LINHA', 'MAX_MODELO', 'ITEM_ESTOQ',
       'BITOLA_FAS', 'MATERIAL_F', 'ISOLAMENTO', 'ITEM_EST00', 'BITOLA_NEU',
       'MATERIAL_N', 'ISOLAMEN00', 'TIPO_COBER', 'ENCORDOAME', 'A1', 'A2',
       'A3', 'A4', 'A5', 'A6', 'A1_NEUTRO', 'A2_NEUTRO', 'A3_NEUTRO',
       'A4_NEUTRO', 'A5_NEUTRO', 'A6_NEUTRO', 'CODIGO_LIN', 'LINHA',
       'MAX_ALIMEN', 'NOME', 'ALIMENTADO', 'LONG', 'LAT', 'Q__z', 'geometry'],
      dtype='object')

In [14]:
gdf_trecho_mt.head()

,CODIGO,COMPRIMENT,COMPRIME00,FASES,TIPO_INSTA,TENSAO_OPE,PROPRIETAR,MAX_LINHA,MAX_MODELO,ITEM_ESTOQ,...,A6_NEUTRO,CODIGO_LIN,LINHA,MAX_ALIMEN,NOME,ALIMENTADO,LONG,LAT,Q__z,geometry
0,617676.0,30.2655,17.4183,ABC,Aéreo,NaN,Light,615303,105925008,323201,...,00,615303.0,LDA CAMELIA,613501,LDA CAMELIA,LDA CAMELIA,-43.371689,-22.876506,NaN,"LINESTRING (-43.37169 -22.87651, -43.37161 -22..."
1,617700.0,26.1069,21.1069,ABC,Aéreo,13.8,Light,615303,105925005,323002,...,00,615303.0,LDA CAMELIA,613501,LDA CAMELIA,LDA CAMELIA,-43.371629,-22.876328,NaN,"LINESTRING (-43.37163 -22.87633, -43.37172 -22..."
2,653264.0,56.9716,56.9716,ABC,Aéreo,NaN,Light,615100,105925008,323201,...,00,615100.0,LDA MAFRA,613489,LDA MAFRA,LDA MAFRA,-43.372710,-22.886731,NaN,"LINESTRING (-43.37271 -22.88673, -43.37310 -22..."
3,653360.0,39.1192,39.1192,ABC,Aéreo,NaN,Light,615100,105925008,323201,...,00,615100.0,LDA MAFRA,613489,LDA MAFRA,LDA MAFRA,-43.371362,-22.888049,NaN,"LINESTRING (-43.37136 -22.88805, -43.37162 -22..."
4,653390.0,63.6026,63.6026,ABC,Aéreo,NaN,Light,615100,105925008,323201,...,00,615100.0,LDA MAFRA,613489,LDA MAFRA,LDA MAFRA,-43.372033,-22.887383,NaN,"LINESTRING (-43.37203 -22.88738, -43.37247 -22..."

In [23]:
gdf_trecho_mt['LINHA'].value_counts()

LINHA
LDA RODU           1413
LDA BELAVI         1406
LDA TABOLEIRO      1401
LDA VILAMIL        1266
LDA JEQUITIBA      1166
                   ...
LDA PROJAC           32
LDA TOPSHOPPING      30
LDS 24794             9
LRA R SEVERIANO       9
LDS 29436             1
Name: count, Length: 339, dtype: int64

# leitura ar

In [15]:
pasta_AR='D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/8. Área de risco/0.4 - Poligonais áreas de risco/'
file_suffixes = ['ACAC.json', 'ASRO.geojson', 'COMUNIDADES_DOMINADAS_PELA_MILICIA.geojson', 'COMUNIDADES_DOMINADAS_PELO_AMIGOS_DOS_AMIGOS.geojson', 'COMUNIDADES_DOMINADAS_PELO_COMANDO_VEMELHO.geojson', 'COMUNIDADES_DOMINADAS_PELO_TERCEIRO_COMANDO_PURO.geojson']

In [16]:
shp_AR0 =gpd.read_file(pasta_AR +'ACAC.json')
shp_AR1 =gpd.read_file(pasta_AR +'ASRO.geojson')
shp_AR2 =gpd.read_file(pasta_AR +'COMUNIDADES_DOMINADAS_PELA_MILICIA.geojson')
shp_AR3 =gpd.read_file(pasta_AR +'COMUNIDADES_DOMINADAS_PELO_AMIGOS_DOS_AMIGOS.geojson')
shp_AR4 =gpd.read_file(pasta_AR +'COMUNIDADES_DOMINADAS_PELO_COMANDO_VEMELHO.geojson')
shp_AR5 =gpd.read_file(pasta_AR +'COMUNIDADES_DOMINADAS_PELO_TERCEIRO_COMANDO_PURO.geojson')

#### Library

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import fiona
from os import listdir
import zipfile
import time
from datetime import datetime
from shapely.ops import unary_union
# import openpyxl
import glob
import pickle
# import pygeos
from shapely.geometry import Point, LineString
import folium
import pyproj
# import cv2
import matplotlib.pyplot as plt
from folium import plugins
import xlsxwriter



#import folium
#from folium import plugins
#from folium import Map, FeatureGroup, Marker, LayerControl, Popup
#from folium.features import DivIcon
import branca.colormap as cm

pd.options.display.max_rows = 10

#import atrb_mcpse

#### function

In [2]:
# Mapas
# Add custom base maps to folium
basemaps = {
    'Google Maps': folium.TileLayer(
        tiles = 'https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
        attr = 'Google',
        name = 'Google Maps'#,
        #overlay = True,
        #control = True
    ),
    'Google Satellite': folium.TileLayer(
        tiles = 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
        attr = 'Google',
        name = 'Google Satellite'#,
        #overlay = True,
        #control = True
    ),
    'Google Terrain': folium.TileLayer(
        tiles = 'https://mt1.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',
        attr = 'Google',
        name = 'Google Terrain'#,
        #overlay = True,
        #control = True
    ),
    'Google Satellite Hybrid': folium.TileLayer(
        tiles = 'https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',
        attr = 'Google',
        name = 'Google Satellite'#,
        #overlay = True,
        #control = True
    ),
    'Esri Satellite': folium.TileLayer(
        tiles = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attr = 'Esri',
        name = 'Esri Satellite'#,
        #overlay = True,
        #control = True
    ),
    'CartoDB positron': folium.TileLayer(
        tiles = 'CartoDB positron',
        attr = 'CartoDB',
        name = 'Light Map'#,
        #overlay = True,
        #control = True
    )  
 }

def mapa(df, indicadores, df2): 
    
    df_colormap = cm.LinearColormap(
    ['blue', 'red'],
     vmin= 0, vmax=1,    
    caption= indicadores + ' Color Scale' #Caption for Color scale or Legend
    )
   ### Centroides Localidades 
    sim_geo = gpd.GeoSeries(df['geometry'])
    geo_json_data = df.to_json()
    #centroides = df.iloc[[0]].to_crs(22182).centroid.to_crs(4326)
    #centroide=df.iloc[[0]].to_crs(22182).centroid.to_crs(4326)
    centroides = df.iloc[[0]].centroid
    centroide=df.iloc[[0]].centroid

    mapa = folium.Map([centroide.y,centroide.x ],
                      zoom_start=8.3,
                      width=800, height=600,
                      tiles=None        )
    
    
    
        # Add custom basemaps
    basemaps['Google Maps'].add_to(mapa)
    basemaps['Google Satellite Hybrid'].add_to(mapa)
    basemaps['Google Satellite'].add_to(mapa)
    basemaps['Google Terrain'].add_to(mapa)
    basemaps['Esri Satellite'].add_to(mapa)
    basemaps['CartoDB positron'].add_to(mapa)
    folium.TileLayer('CartoDB positron',name="Light Map",control=False).add_to(mapa)
    
     


    style_function = lambda feature: {
           'fillColor': df_colormap(feature['properties'][indicadores]),
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.3
                }

    
    folium.GeoJson(
        geo_json_data,
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(
                fields = [indicadores],
                localize=False)

        ).add_to(mapa)
    
    
    if len(df2) >0:
        style_function = lambda feature: {
            'fillColor': 'red',
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.3
                }
        folium.GeoJson(df2, style_function=style_function).add_to(mapa)
    
    folium.map.CustomPane('labels').add_to(mapa)
    folium.TileLayer('CartoDBPositronOnlyLabels',
                     pane='labels').add_to(mapa)

    #fullscreen
    plugins.Fullscreen().add_to(mapa)

    df_colormap.add_to(mapa) 
    # Add a layer control panel to the map.
    #mapa.add_child(folium.LayerControl())
    folium.LayerControl().add_to(mapa)   
    
    return mapa

def mapa_atrib(df, label,df2): 

    ### Centroides Localidades 
    sim_geo = gpd.GeoSeries(df['geometry'])
    geo_json_data = df.to_json()
    df['x']=df.centroid.x
    df['y']=df.centroid.y
    centroides = df.iloc[[0]].centroid
    centroide=df.iloc[[0]].centroid
    
    mapa = folium.Map([centroide.y,centroide.x ],
                      zoom_start=14,
                      width=800, height=600,
                      tiles=None        )
    minimap = plugins.MiniMap(toggle_display=True)
    mapa.add_child(minimap)
    #plugins.ScrollZoomToggler().add_to(mapa)
    plugins.Fullscreen(position="topright").add_to(mapa)
    
        # Add custom basemaps
    basemaps['Google Maps'].add_to(mapa)
    basemaps['Google Satellite Hybrid'].add_to(mapa)
    basemaps['Google Satellite'].add_to(mapa)
    basemaps['Google Terrain'].add_to(mapa)
    basemaps['Esri Satellite'].add_to(mapa)
    basemaps['CartoDB positron'].add_to(mapa)
    folium.TileLayer('CartoDB positron',name="Light Map",control=False).add_to(mapa)
    
    
    style_function = lambda feature: {
        'fillColor': 'red',
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.3
            }
    folium.GeoJson(df, style_function=style_function).add_to(mapa)
    folium.GeoJson(df2).add_to(mapa)
    # add marker one by one on the map
    for i in range(0,len(df)):
       folium.Marker(
          location=[df.iloc[i]['y'],df.iloc[i]['x']],
          popup=df.iloc[i][label],
          icon=folium.DivIcon(html=f"""<div style="font-family: courier new; color: blue">{df.iloc[i][label]}</div>""")
       ).add_to(mapa)

    return mapa

### Path and read

In [18]:
path_fme = "D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME"
# path_res = "D:/2. Light_2023/Inventário/4. Resultados/2. Calculadora/"
# path_excel = "D:/2. Light_2023/Inventário/4. Resultados/2. Calculadora/Circuitos/"

In [19]:
path_fme

'D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME'

In [20]:
import os
import glob
import fiona

def listar_arquivos_shp(path_fme):
    # Obtém todos os arquivos .shp na pasta fornecida
    padrao = os.path.join(path_fme, '*.shp')
    arquivos_shp = glob.glob(padrao)

    # Imprime o caminho de cada arquivo .shp
    for arquivo_shp in arquivos_shp:
        print(arquivo_shp)

    # Informa se não houver arquivos .shp na pasta
    if not arquivos_shp:
        print("Nenhum arquivo .shp encontrado na pasta.")

if __name__ == "__main__":
    # Substitua 'caminho/para/sua/pasta' pelo caminho da pasta desejada
    caminho_da_pasta = path_fme
    listar_arquivos_shp(caminho_da_pasta)

D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME\Banco de Capacitores.shp
D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME\Fly Tap BT.shp
D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME\Fly Tap.shp
D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME\Transformador.shp
D:/GIT/2022_23_LIGHT_Sust_Concessao/4. Execução/4. Inventário de campo/2. Informações/5. Amostragem/1. FME/Extrações no FME\Trecho MT.shp

In [21]:
Trecho_MT = gpd.read_file(path_fme + "/Trecho MT.shp")

# Banco de Capacitores

In [8]:
BC = gpd.read_file(path_fme + "/Banco de Capacitores.shp")

In [10]:
BC.columns

Index(['CODIGO', 'MATRICULA', 'NUM_UNIDAD', 'NUM_UNID00', 'CLASSE_TEN',
       'POTENCIA', 'TIPO_CONTR', 'SUB_TIPO_C', 'TIPO_LIGAC', 'CORRENTE_N',
       'CAP_NOMINA', 'ESTADO', 'FASES', 'MAX_LINHA', 'LOTE', 'NOME_LINHA',
       'LONG', 'LAT', 'Q__z', 'geometry'],
      dtype='object')

In [15]:
BC

,CODIGO,MATRICULA,NUM_UNIDAD,NUM_UNID00,CLASSE_TEN,POTENCIA,TIPO_CONTR,SUB_TIPO_C,TIPO_LIGAC,CORRENTE_N,CAP_NOMINA,ESTADO,FASES,MAX_LINHA,LOTE,NOME_LINHA,LONG,LAT,Q__z,geometry
0,1646082.0,BC81417,3.0,3.0,"15,0 kV",300 KVAR,Direto,FIXO,Estrela,NaN,50.0,Ligado,ABC,615104,NaN,LDA MALOCA,-43.264677,-22.869311,NaN,POINT (-43.26468 -22.86931)
1,1646087.0,BC95011,NaN,NaN,"15,0 kV",300 KVAR,Direto,FIXO,Delta,NaN,50.0,Ligado,ABC,615343,NaN,LDA DONABEL,-43.253919,-22.870021,NaN,POINT (-43.25392 -22.87002)
2,1646092.0,BC81466,NaN,NaN,"15,0 kV",300 KVAR,Direto,FIXO,Delta,NaN,50.0,Ligado,ABC,615343,NaN,LDA DONABEL,-43.249259,-22.869220,NaN,POINT (-43.24926 -22.86922)
3,1646097.0,BC81423,NaN,NaN,"15,0 kV",300 KVAR,Direto,FIXO,Estrela,NaN,50.0,Ligado,ABC,615174,NaN,LDA PROCLAMACAO,-43.255087,-22.869407,NaN,POINT (-43.25509 -22.86941)
4,1646102.0,BC95010,NaN,NaN,"15,0 kV",300 KVAR,Direto,FIXO,Estrela,NaN,100.0,Ligado,ABC,615286,NaN,LDA BERGAMINI,-43.296459,-22.904189,NaN,POINT (-43.29646 -22.90419)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,10935793.0,BC85773,1.0,3.0,"15,0 kV",300 KVAR,Direto,MANUAL,Estrela,NaN,50.0,Ligado,ABC,496893099,NaN,LDA BUENO,-43.351127,-22.961184,NaN,POINT (-43.35113 -22.96118)
285,18945350.0,BC534278,3.0,3.0,"15,0 kV",300 KVAR,Direto,MANUAL,Estrela,NaN,50.0,Ligado,ABC,18796561,NaN,LDA MACONARIA,-43.204100,-22.111362,NaN,POINT (-43.20410 -22.11136)
286,32389758.0,BC4397,NaN,NaN,"15,0 kV",300 KVAR,Direto,MANUAL,Estrela,NaN,300.0,Ligado,ABC,18796622,NaN,LDA MORADA,-44.114825,-22.540969,NaN,POINT (-44.11482 -22.54097)
287,1646752.0,BC95008,3.0,3.0,"15,0 kV",300 KVAR,Direto,FIXO,Estrela,NaN,50.0,Ligado,ABC,615125,NaN,LDA MELGACO,-43.295522,-22.816600,NaN,POINT (-43.29552 -22.81660)
288,15003668.0,BC86653,1.0,3.0,"15,0 kV",300 KVAR,Direto,FIXO,Estrela,NaN,50.0,Ligado,ABC,10391223,NaN,LDA LARA,-43.378645,-22.921929,NaN,POINT (-43.37865 -22.92193)

# Fly Tap BT

In [12]:
FT_BT = gpd.read_file(path_fme + "/Fly Tap BT.shp")

In [14]:
FT_BT.columns

Index(['CODIGO', 'MATRICULA', 'MAX_CIRCUI', 'NOME', 'MAX_TRANSF', 'MAX_LINHA',
       'NOME_LINHA', 'LONG', 'LAT', 'Q__z', 'geometry'],
      dtype='object')

In [16]:
FT_BT['NOME_LINHA'].value_counts()

NOME_LINHA
LDA CURIE          20
LDA ALMIRANTE      18
LDA AMAZONAS       13
LDA SIDEROPOLIS    12
LDA CICUTA         12
                   ..
LDA ZOOTECNICO      1
LDA CERAMICA        1
LDA RICA            1
LDA ITAJAI          1
LDA GURUPI          1
Name: count, Length: 78, dtype: int64

# Fly Tap

In [ ]:
FT = gpd.read_file(path_fme + "/Fly Tap.shp")

In [ ]:
FT.columns

Index(['CODIGO', 'MATRICULA', 'MAX_CIRCUI', 'NOME', 'MAX_TRANSF', 'MAX_LINHA',
       'NOME_LINHA', 'LONG', 'LAT', 'Q__z', 'geometry'],
      dtype='object')

In [ ]:
FT['NOME_LINHA'].value_counts()

NOME_LINHA
LDA CURIE          20
LDA ALMIRANTE      18
LDA AMAZONAS       13
LDA SIDEROPOLIS    12
LDA CICUTA         12
                   ..
LDA ZOOTECNICO      1
LDA CERAMICA        1
LDA RICA            1
LDA ITAJAI          1
LDA GURUPI          1
Name: count, Length: 78, dtype: int64

# Trecho MT

In [17]:
Trecho_MT = gpd.read_file(path_fme + "/Trecho MT.shp")

NameError: name 'path_fme' is not defined

In [3]:
Trecho_MT['NOME_LINHA'].value_counts().describe()

NameError: name 'Trecho_MT' is not defined

# Transformador

In [20]:
TRAFO = gpd.read_file(path_fme + "/Transformador.shp")

In [21]:
TRAFO['NOME_LINHA'].value_counts()

NOME_LINHA
LDA SANTAREM / SERV.    270
LDA JEQUITIBA           175
LDA BELAVI              168
LDA GADOBAN             153
LDA RODU                147
                       ...
LDA OURO                  2
LDS 61704                 1
LDA DAGRACA               1
LDA ILHAPURA              1
LDA SALVALENDE            1
Name: count, Length: 295, dtype: int64

In [9]:
alimentador = CTMT[CTMT['COD_ID'].isin(NOME_CT)]
alimentador = alimentador[['COD_ID', 'BARR', 'SUB', 'PAC_INI', 'TEN_NOM','NOME']]
alimentador

Empty DataFrame
Columns: [COD_ID, BARR, SUB, PAC_INI, TEN_NOM, NOME]
Index: []

In [10]:
CTMT.to_csv('CTMT.csv', sep = ';')

# SEGMENTOS BT

In [11]:
SSDBT =   pd.read_pickle(path_info + 'SSDBT.pkl')
SSDBT.columns

Index(['COD_ID', 'PN_CON_1', 'PN_CON_2', 'UNI_TR_MT', 'CTMT', 'CT_COD_OP',
       'UNI_TR_AT', 'SUB', 'CONJ', 'ARE_LOC', 'FAS_CON', 'DIST', 'PAC_1',
       'PAC_2', 'TIP_INST', 'TIP_CND', 'POS', 'ODI', 'TI', 'CM', 'SITCONT',
       'COMP', 'DESCR', 'geometry', 'file', 'TIP_INST_dic', 'len'],
      dtype='object')

In [12]:
df_SSDBT = SSDBT[SSDBT['CTMT'].isin(alimentador['COD_ID'])]

In [13]:
df_SSDBT['CTMT'].value_counts()

Series([], Name: count, dtype: int64)

### Distâncias (m) e Quantidades

In [14]:
# colunas_agrupadas = ['DIST','CTMT']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_INST_dic' ]
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND']
colunas_agrupadas = ['DIST','CTMT','TIP_INST_dic', 'FAS_CON']

In [15]:
colunas_agrupadas[1:]

['CTMT', 'TIP_INST_dic', 'FAS_CON']

In [16]:
check_BT = df_SSDBT.groupby(colunas_agrupadas[1]).agg({'DIST': 'count', 'COMP': 'sum' ,'len' : 'sum' }).reset_index()

In [17]:
df_SSDBT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count', 'COMP': 'sum' ,'len' : 'sum' }).reset_index()

Empty DataFrame
Columns: [CTMT, TIP_INST_dic, FAS_CON, DIST, COMP, len]
Index: []

### SEGCON

In [18]:
SEGCON = pd.read_pickle(path_info + "SEGCON.pkl")
SEGCON.columns

Index(['COD_ID', 'DIST', 'GEOM_CAB', 'FORM_CAB', 'BIT_FAS_1', 'BIT_FAS_2',
       'BIT_FAS_3', 'BIT_NEU', 'MAT_FAS_1', 'MAT_FAS_2', 'MAT_FAS_3',
       'MAT_NEU', 'ISO_FAS_1', 'ISO_FAS_2', 'ISO_FAS_3', 'ISO_NEU', 'CND_FAS',
       'R1', 'X1', 'R_REGUL', 'FTRCNV', 'CNOM', 'CMAX', 'TUC_FAS', 'A1_FAS',
       'A2_FAS', 'A3_FAS', 'A4_FAS', 'A5_FAS', 'A6_FAS', 'TUC_NEU', 'A1_NEU',
       'A2_NEU', 'A3_NEU', 'A4_NEU', 'A5_NEU', 'A6_NEU', 'UAR', 'DESCR',
       'geometry', 'file', 'GEOM_CAB_dic', 'FORM_CAB_dic', 'BIT_FAS_1_dic',
       'BIT_FAS_2_dic', 'BIT_FAS_3_dic', 'BIT_NEU_dic', 'MAT_FAS_1_dic',
       'MAT_FAS_2_dic', 'MAT_FAS_3_dic', 'MAT_NEU_dic', 'ISO_FAS_1_dic',
       'ISO_FAS_2_dic', 'ISO_FAS_3_dic', 'ISO_NEU_dic', 'TUC_FAS_dic',
       'A1_FAS_dic', 'A2_FAS_dic', 'A3_FAS_dic', 'A4_FAS_dic', 'A5_FAS_dic',
       'A6_FAS_dic', 'TUC_NEU_dic', 'A1_NEU_dic', 'A2_NEU_dic', 'A3_NEU_dic',
       'A4_NEU_dic', 'A5_NEU_dic', 'A6_NEU_dic'],
      dtype='object')

In [19]:
#trocar
## DIST - quantidade
## len - Geo_comp

## Tucagem
# colunas_agrupadas_segcon = ['COD_ID','TUC_FAS', 'A1_FAS','A2_FAS','A3_FAS', 'A4_FAS', 'A5_FAS', 'A6_FAS']

## Personalizado
# colunas_agrupadas_segcon = ['COD_ID','GEOM_CAB_dic','FORM_CAB','FORM_CAB_dic', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']
colunas_agrupadas_segcon = ['COD_ID','GEOM_CAB_dic', 'FORM_CAB_dic',                                # geometria e formação    
                            'BIT_FAS_1_dic','BIT_FAS_2_dic','BIT_FAS_3_dic','BIT_NEU_dic',         # bitola
                            'MAT_FAS_1_dic','MAT_FAS_2_dic', 'MAT_FAS_3_dic', 'MAT_NEU_dic',    # material
                            'ISO_FAS_1_dic', 'ISO_FAS_2_dic', 'ISO_FAS_3_dic', 'ISO_NEU_dic',                    # isolador 
                            'TUC_FAS_dic', 'A1_FAS_dic', 'A2_FAS_dic', 'A3_FAS_dic', 'A4_FAS_dic', 'A5_FAS_dic', 'A6_FAS_dic',  # Tuc Fase
                            'TUC_NEU_dic', 'A1_NEU_dic','A2_NEU_dic', 'A3_NEU_dic', 'A4_NEU_dic', 'A5_NEU_dic', 'A6_NEU_dic',   # Tuc Neutro                         
                            'CND_FAS']                                                              # Condutor por fase

In [20]:
sum_SEG_BT = df_SSDBT.merge(SEGCON[colunas_agrupadas_segcon], left_on = 'TIP_CND', right_on = 'COD_ID', how ='left').groupby(colunas_agrupadas[1:] +colunas_agrupadas_segcon[1:] ).agg({'DIST': 'count', 'COMP': 'sum' ,'len' : 'sum' }).reset_index()
sum_SEG_BT.rename(columns={'DIST': 'QUANTIDADE', 'len': 'GEO_COMP'}, inplace=True)
sum_SEG_BT['NIVEL_TBL'] = 'BT'
sum_SEG_BT

Empty DataFrame
Columns: [CTMT, TIP_INST_dic, FAS_CON, GEOM_CAB_dic, FORM_CAB_dic, BIT_FAS_1_dic, BIT_FAS_2_dic, BIT_FAS_3_dic, BIT_NEU_dic, MAT_FAS_1_dic, MAT_FAS_2_dic, MAT_FAS_3_dic, MAT_NEU_dic, ISO_FAS_1_dic, ISO_FAS_2_dic, ISO_FAS_3_dic, ISO_NEU_dic, TUC_FAS_dic, A1_FAS_dic, A2_FAS_dic, A3_FAS_dic, A4_FAS_dic, A5_FAS_dic, A6_FAS_dic, TUC_NEU_dic, A1_NEU_dic, A2_NEU_dic, A3_NEU_dic, A4_NEU_dic, A5_NEU_dic, A6_NEU_dic, CND_FAS, QUANTIDADE, COMP, GEO_COMP, NIVEL_TBL]
Index: []

[0 rows x 36 columns]

In [21]:
sum_SEG_BT[sum_SEG_BT['CTMT'] == "PER763"]

Empty DataFrame
Columns: [CTMT, TIP_INST_dic, FAS_CON, GEOM_CAB_dic, FORM_CAB_dic, BIT_FAS_1_dic, BIT_FAS_2_dic, BIT_FAS_3_dic, BIT_NEU_dic, MAT_FAS_1_dic, MAT_FAS_2_dic, MAT_FAS_3_dic, MAT_NEU_dic, ISO_FAS_1_dic, ISO_FAS_2_dic, ISO_FAS_3_dic, ISO_NEU_dic, TUC_FAS_dic, A1_FAS_dic, A2_FAS_dic, A3_FAS_dic, A4_FAS_dic, A5_FAS_dic, A6_FAS_dic, TUC_NEU_dic, A1_NEU_dic, A2_NEU_dic, A3_NEU_dic, A4_NEU_dic, A5_NEU_dic, A6_NEU_dic, CND_FAS, QUANTIDADE, COMP, GEO_COMP, NIVEL_TBL]
Index: []

[0 rows x 36 columns]

# SEGMENTOS  MT

In [22]:
SSDMT =  pd.read_pickle(path_info + 'SSDMT.pkl')
SSDMT.columns

Index(['COD_ID', 'PN_CON_1', 'PN_CON_2', 'CTMT', 'CT_COD_OP', 'UNI_TR_AT',
       'SUB', 'CONJ', 'ARE_LOC', 'DIST', 'PAC_1', 'PAC_2', 'FAS_CON',
       'TIP_INST', 'TIP_CND', 'POS', 'ODI', 'TI', 'CM', 'SITCONT', 'COMP',
       'DESCR', 'geometry', 'file', 'TIP_INST_dic', 'len'],
      dtype='object')

In [23]:
df_SSDMT = SSDMT[SSDMT['CTMT'].isin(alimentador['COD_ID'])]

### Distâncias (m) e Quantidades

In [24]:
check_MT = df_SSDMT.groupby(colunas_agrupadas[1]).agg({'DIST': 'count', 'COMP': 'sum','len' : 'sum' }).reset_index()

In [25]:
df_SSDMT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count', 'COMP': 'sum','len' : 'sum' }).reset_index()

Empty DataFrame
Columns: [CTMT, TIP_INST_dic, FAS_CON, DIST, COMP, len]
Index: []

In [26]:

## Tucagem
# colunas_agrupadas_segcon = ['COD_ID','TUC_FAS', 'A1_FAS','A2_FAS','A3_FAS', 'A4_FAS', 'A5_FAS', 'A6_FAS']

## Personalizado
# colunas_agrupadas_segcon = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [27]:
sum_SEG_MT = df_SSDMT.merge(SEGCON[colunas_agrupadas_segcon], left_on = 'TIP_CND', right_on = 'COD_ID', how ='left').groupby(colunas_agrupadas[1:] +colunas_agrupadas_segcon[1:] ).agg({'DIST': 'count', 'COMP': 'sum' ,'len' : 'sum' }).reset_index()
sum_SEG_MT.rename(columns={'DIST': 'QUANTIDADE', 'len': 'GEO_COMP'}, inplace=True)
sum_SEG_MT['NIVEL_TBL'] = 'MT'
sum_SEG_MT

Empty DataFrame
Columns: [CTMT, TIP_INST_dic, FAS_CON, GEOM_CAB_dic, FORM_CAB_dic, BIT_FAS_1_dic, BIT_FAS_2_dic, BIT_FAS_3_dic, BIT_NEU_dic, MAT_FAS_1_dic, MAT_FAS_2_dic, MAT_FAS_3_dic, MAT_NEU_dic, ISO_FAS_1_dic, ISO_FAS_2_dic, ISO_FAS_3_dic, ISO_NEU_dic, TUC_FAS_dic, A1_FAS_dic, A2_FAS_dic, A3_FAS_dic, A4_FAS_dic, A5_FAS_dic, A6_FAS_dic, TUC_NEU_dic, A1_NEU_dic, A2_NEU_dic, A3_NEU_dic, A4_NEU_dic, A5_NEU_dic, A6_NEU_dic, CND_FAS, QUANTIDADE, COMP, GEO_COMP, NIVEL_TBL]
Index: []

[0 rows x 36 columns]

# Resultado

In [28]:
resultado_alimentadores = pd.concat([sum_SEG_BT,sum_SEG_MT], axis=0 )

In [29]:
resultado_alimentadores.columns

Index(['CTMT', 'TIP_INST_dic', 'FAS_CON', 'GEOM_CAB_dic', 'FORM_CAB_dic',
       'BIT_FAS_1_dic', 'BIT_FAS_2_dic', 'BIT_FAS_3_dic', 'BIT_NEU_dic',
       'MAT_FAS_1_dic', 'MAT_FAS_2_dic', 'MAT_FAS_3_dic', 'MAT_NEU_dic',
       'ISO_FAS_1_dic', 'ISO_FAS_2_dic', 'ISO_FAS_3_dic', 'ISO_NEU_dic',
       'TUC_FAS_dic', 'A1_FAS_dic', 'A2_FAS_dic', 'A3_FAS_dic', 'A4_FAS_dic',
       'A5_FAS_dic', 'A6_FAS_dic', 'TUC_NEU_dic', 'A1_NEU_dic', 'A2_NEU_dic',
       'A3_NEU_dic', 'A4_NEU_dic', 'A5_NEU_dic', 'A6_NEU_dic', 'CND_FAS',
       'QUANTIDADE', 'COMP', 'GEO_COMP', 'NIVEL_TBL'],
      dtype='object')

In [30]:
check_BT['NIVEL_TBL'] = "BT"
check_MT['NIVEL_TBL'] = "MT"

res_check = pd.concat([check_BT,check_MT], axis=0 )
res_check = resultado_alimentadores.groupby(['CTMT', 'NIVEL_TBL']).agg({'QUANTIDADE': 'sum', 'COMP': 'sum' ,'GEO_COMP' : 'sum' }).reset_index().merge(res_check, on =['CTMT','NIVEL_TBL'] )
res_check['DIF_quant'] = res_check['QUANTIDADE'] - res_check['DIST']
res_check['DIF_comp'] = res_check['COMP_x'] - res_check['COMP_y']

In [31]:
res_check[(res_check['DIF_quant'] !=- 0) | (res_check['DIF_comp'] != 0)]

Empty DataFrame
Columns: [QUANTIDADE, COMP_x, GEO_COMP, CTMT, DIST, COMP_y, len, NIVEL_TBL, DIF_quant, DIF_comp]
Index: []

In [32]:
resultado_alimentadores.to_csv(path_res + 'res_alimentadores_BDGD.csv', sep=';', encoding='latin1', errors='ignore')

# Equipametos

### CRMT

In [131]:


un =  ["UNCRMT", "UN_CR"]
eq = ["EQCR"]

In [132]:
UNCRMT =   pd.read_pickle(path_info + un[0] + ".pkl")
UNCRMT.columns

Index(['COD_ID', 'DIST', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID', 'POT_NOM', 'PAC_1',
       'PAC_2', 'CTMT', 'UNI_TR_AT', 'SUB', 'CONJ', 'MUN', 'ARE_LOC',
       'DAT_CON', 'BANC', 'POS', 'DESCR', 'geometry', 'file', 'TIP_UNID_dic',
       'TIP_UNID_detail_dic', 'POT_NOM_UN_kVAr_dic'],
      dtype='object')

In [133]:
UNCRMT['CTMT']

0        PER763
1       VGE3919
2      CUR33000
3      GNB34723
4       VGE3758
         ...
786    CMTTSL42
787     REC0001
788     CMR9663
789    CMTTSL42
790     CMR9663
Name: CTMT, Length: 791, dtype: object

In [134]:
df_UNCRMT = UNCRMT[UNCRMT['CTMT'].isin(alimentador['COD_ID'])]

In [135]:
# colunas_agrupadas = ['CTMT','DIST']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_UNID']
colunas_agrupadas = ['DIST','CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic','TIP_UNID_detail_dic', 'POT_NOM_UN_kVAr_dic']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND','TIP_INST', 'FAS_CON']

In [136]:
df_UNCRMT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count' }).reset_index()

,CTMT,FAS_CON,SIT_ATIV,TIP_UNID_dic,TIP_UNID_detail_dic,POT_NOM_UN_kVAr_dic,DIST
0,PER763,ABC,AT,10_UNIDADE COMPENSADORA DE REATIVO,10_BANCO DE CAPACITORES PARALELO,3600,3
1,VRD014,ABC,AT,10_UNIDADE COMPENSADORA DE REATIVO,10_BANCO DE CAPACITORES PARALELO,600,1

In [137]:
EQCR =   pd.read_pickle(path_info + eq[0] + ".pkl")
EQCR.columns

Index(['COD_ID', 'DIST', 'TIP_INST', 'UN_CR', 'ODI', 'TI', 'CM', 'TUC', 'A1',
       'A2', 'A3', 'A4', 'A5', 'A6', 'UAR', 'IDUC', 'SITCONT', 'DAT_IMO',
       'DESCR', 'GRU_TEN', 'geometry', 'file', 'TUC_dic', 'TUC_A1',
       'TUC_A1_dic', 'TUC_A2', 'TUC_A2_dic', 'TUC_A3', 'TUC_A3_dic', 'TUC_A4',
       'TUC_A4_dic', 'TUC_A5', 'TUC_A5_dic', 'TUC_A6', 'TUC_A6_dic'],
      dtype='object')

In [138]:

## Tucagem
# colunas_agrupadas_eq = ['COD_ID', un[1],'TUC', 'A1','A2','A3', 'A4', 'A5', 'A6', 'GRU_TEN']

## Personalizado
colunas_agrupadas_eq = ['COD_ID','TIP_INST','UN_CR','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']

In [139]:
agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_eq[1:]}

# Realize o merge e, em seguida, agrupe e aplique as agregações
sum_EQCR_MT = df_UNCRMT.merge(EQCR[colunas_agrupadas_eq], left_on='COD_ID', right_on=un[1], how='left') \
    .groupby(colunas_agrupadas[1:]) \
    .agg({**agg_dict, 'DIST': 'count'}) \
    .reset_index()

sum_EQCR_MT['nivel_tbl'] = 'MT'
sum_EQCR_MT.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# sum_EQCR_MT['Ativo'] = 'TRANSFORMADOR'
sum_EQCR_MT.head().style

In [140]:
sum_EQCR_MT.to_csv(path_res + 'res_CRMT.csv', sep=';', encoding='latin1', errors='ignore')

### REMT

In [141]:
#REMT


un =  ["UNREMT", "UN_RE"]
eq = ["EQRE"]

In [142]:
UNREMT =   pd.read_pickle(path_info + un[0] + ".pkl")
UNREMT.columns

Index(['COD_ID', 'DIST', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID', 'TIP_REGU',
       'PAC_1', 'PAC_2', 'CTMT', 'UNI_TR_AT', 'SUB', 'CONJ', 'MUN', 'DAT_CON',
       'BANC', 'POS', 'DESCR', 'geometry', 'file', 'TIP_UNID_dic',
       'TIP_UNID_detail_dic'],
      dtype='object')

In [143]:
UNREMT['CTMT']

0       AGR008
1       TRS013
2       CEN003
3       CEN001
4       CAM020
        ...
10     MRT2929
11      SCI006
12    SCO33618
13      STS006
14      CEN005
Name: CTMT, Length: 15, dtype: object

In [144]:
df_UNREMT = UNREMT[UNREMT['CTMT'].isin(alimentador['COD_ID'])]

In [145]:
# colunas_agrupadas = ['CTMT','DIST']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_UNID']
colunas_agrupadas = ['DIST','CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic','TIP_UNID_detail_dic']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND','TIP_INST', 'FAS_CON']

In [146]:
df_UNREMT

,COD_ID,DIST,FAS_CON,SIT_ATIV,TIP_UNID,TIP_REGU,PAC_1,PAC_2,CTMT,UNI_TR_AT,...,CONJ,MUN,DAT_CON,BANC,POS,DESCR,geometry,file,TIP_UNID_dic,TIP_UNID_detail_dic
0,658201639,382,ABC,AT,14,DF,MT_639495,MT_639495_2,AGR008,1248369,...,15045,3304557,09/06/2020,1,PD,None,POINT (-43.29478 -22.81549),BD31122022_25022023/UNREMT.shp,14_UNIDADE REGULADORA,14_REGULADOR AUTOMÁTICO DE TENSÃO

In [147]:
df_UNREMT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count' }).reset_index()

,CTMT,FAS_CON,SIT_ATIV,TIP_UNID_dic,TIP_UNID_detail_dic,DIST
0,AGR008,ABC,AT,14_UNIDADE REGULADORA,14_REGULADOR AUTOMÁTICO DE TENSÃO,1

### EQRE

In [148]:
EQRE = pd.read_pickle(path_info + eq[0] + ".pkl")
EQRE.columns

Index(['COD_ID', 'DIST', 'TIP_INST', 'UN_RE', 'POT_NOM', 'TEN_REG',
       'LIG_FAS_P', 'LIG_FAS_S', 'COR_NOM', 'REL_TP', 'REL_TC', 'ODI', 'TI',
       'CM', 'TUC', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'UAR', 'IDUC',
       'SITCONT', 'DAT_IMO', 'PER_FER', 'PER_TOT', 'R', 'XHL', 'DESCR',
       'GRU_TEN', 'geometry', 'file', 'TUC_dic', 'TUC_A1', 'TUC_A1_dic',
       'TUC_A2', 'TUC_A2_dic', 'TUC_A3', 'TUC_A3_dic', 'TUC_A4', 'TUC_A4_dic',
       'TUC_A5', 'TUC_A5_dic', 'TUC_A6', 'TUC_A6_dic'],
      dtype='object')

In [149]:

## Tucagem
colunas_agrupadas_eq = ['COD_ID','TIP_INST','UN_RE','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']

## Personalizado
# colunas_agrupadas_eq = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [150]:
colunas_agrupadas[1:]

['CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic', 'TIP_UNID_detail_dic']

In [151]:
agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_eq[1:]}

# Realize o merge e, em seguida, agrupe e aplique as agregações
sum_EQRE_MT = df_UNREMT.merge(EQRE[colunas_agrupadas_eq], left_on='COD_ID', right_on=un[1], how='left') \
    .groupby(colunas_agrupadas[1:]) \
    .agg({**agg_dict, 'DIST': 'count'}) \
    .reset_index()

sum_EQRE_MT['nivel_tbl'] = 'MT'
sum_EQRE_MT.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# sum_EQRE_MT['Ativo'] = 'TRANSFORMADOR'
sum_EQRE_MT.head().style

In [152]:
sum_EQRE_MT.to_csv(path_res + 'res_REMT.csv', sep=';', encoding='latin1', errors='ignore')

### SEMT

In [153]:
#seMT


un =  ["UNSEMT", "UN_SE"]
eq = ["EQSE"]

In [154]:
UNSEMT =   pd.read_pickle(path_info + un[0] + ".pkl")
UNSEMT.columns

Index(['COD_ID', 'DIST', 'PAC_1', 'PAC_2', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID',
       'P_N_OPE', 'CAP_ELO', 'COR_NOM', 'TLCD', 'DAT_CON', 'POS', 'CTMT',
       'UNI_TR_AT', 'SUB', 'CONJ', 'MUN', 'ARE_LOC', 'DESCR', 'geometry',
       'file', 'TIP_UNID_dic', 'TIP_UNID_detail_dic'],
      dtype='object')

In [155]:
df_UNSEMT = UNSEMT[UNSEMT['CTMT'].isin(alimentador['COD_ID'])]

In [156]:
# colunas_agrupadas = ['CTMT','DIST']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
colunas_agrupadas = ['DIST','CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic','TIP_UNID_detail_dic']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_REGU']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND','TIP_INST', 'FAS_CON']

In [157]:
df_UNSEMT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count' }).reset_index()

      CTMT FAS_CON SIT_ATIV             TIP_UNID_dic TIP_UNID_detail_dic  DIST
0   AGR008     ABC       AT  19_UNIDADE SECCIONADORA       19_CHAVE FACA    19
1   AGR008     ABC       AT  22_UNIDADE SECCIONADORA    22_CHAVE FUSÍVEL     5
2   AGR008     ABC       AT  29_UNIDADE SECCIONADORA        29_DISJUNTOR     1
3   AGR008     ABC       AT  32_UNIDADE SECCIONADORA        32_RELIGADOR     1
4   AGR008     ABC       AT  35_UNIDADE SECCIONADORA  35_SECCIONALIZADOR     1
..     ...     ...      ...                      ...                 ...   ...
22  VRD014     ABC       AT  19_UNIDADE SECCIONADORA       19_CHAVE FACA    22
23  VRD014     ABC       AT  22_UNIDADE SECCIONADORA    22_CHAVE FUSÍVEL     9
24  VRD014     ABC       AT  29_UNIDADE SECCIONADORA        29_DISJUNTOR     1
25  VRD014     ABC       AT  32_UNIDADE SECCIONADORA        32_RELIGADOR     2
26  VRD014     ABC       AT  35_UNIDADE SECCIONADORA  35_SECCIONALIZADOR     3

[27 rows x 6 columns]

### EQSE

In [158]:
EQSE = pd.read_pickle(path_info + eq[0] + ".pkl")
EQSE.columns

Index(['COD_ID', 'DIST', 'TIP_INST', 'UN_SE', 'CLAS_TEN', 'ELO_FSV', 'MEI_ISO',
       'FAS_CON', 'COR_NOM', 'ODI', 'TI', 'CM', 'TUC', 'A1', 'A2', 'A3', 'A4',
       'A5', 'A6', 'UAR', 'IDUC', 'SITCONT', 'DAT_IMO', 'ABER_CRG', 'DESCR',
       'GRU_TEN', 'geometry', 'file', 'TUC_dic', 'TUC_A1', 'TUC_A1_dic',
       'TUC_A2', 'TUC_A2_dic', 'TUC_A3', 'TUC_A3_dic', 'TUC_A4', 'TUC_A4_dic',
       'TUC_A5', 'TUC_A5_dic', 'TUC_A6', 'TUC_A6_dic'],
      dtype='object')

In [159]:

## Tucagem
colunas_agrupadas_eq = ['COD_ID','TIP_INST','UN_SE','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']

## Personalizado
# colunas_agrupadas_eq = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [160]:
colunas_agrupadas[1:]

['CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic', 'TIP_UNID_detail_dic']

In [161]:
agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_eq[1:]}

# Realize o merge e, em seguida, agrupe e aplique as agregações
sum_EQSE_MT = df_UNSEMT.merge(EQSE[colunas_agrupadas_eq], left_on='COD_ID', right_on=un[1], how='left') \
    .groupby(colunas_agrupadas[1:]) \
    .agg({**agg_dict, 'DIST': 'count'}) \
    .reset_index()

sum_EQSE_MT['nivel_tbl'] = 'MT'
sum_EQSE_MT.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# sum_EQSE_MT['Ativo'] = 'TRANSFORMADOR'
sum_EQSE_MT.head().style

In [162]:
sum_EQSE_MT.to_csv(path_res + 'res_SEMT.csv', sep=';', encoding='latin1', errors='ignore')

### TRMT

In [163]:
#trMT


un =  ["UNTRMT", "UNI_TR_MT"]
eq = ["EQTRMT"]

In [164]:
UNTRMT =   pd.read_pickle(path_info + un[0] + ".pkl")
UNTRMT.columns

Index(['COD_ID', 'DIST', 'PAC_1', 'PAC_2', 'PAC_3', 'FAS_CON_P', 'FAS_CON_S',
       'FAS_CON_T', 'SIT_ATIV', 'TIP_UNID', 'POS', 'ATRB_PER', 'TEN_LIN_SE',
       'CAP_ELO', 'CAP_CHA', 'TAP', 'ARE_LOC', 'CONF', 'POSTO', 'POT_NOM',
       'PER_FER', 'PER_TOT', 'DAT_CON', 'CTMT', 'UNI_TR_AT', 'SUB', 'CONJ',
       'MUN', 'BANC', 'TIP_TRAFO', 'MRT', 'DESCR', 'geometry', 'file',
       'TIP_UNID_dic', 'TIP_UNID_detail_dic'],
      dtype='object')

In [165]:
df_UNTRMT = UNTRMT[UNTRMT['CTMT'].isin(alimentador['COD_ID'])]

In [166]:
# colunas_agrupadas = ['CTMT','DIST']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
colunas_agrupadas = ['DIST','CTMT', 'SIT_ATIV','POT_NOM', 'TIP_UNID_dic','TIP_UNID_detail_dic']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_REGU']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND','TIP_INST', 'FAS_CON']

In [167]:
colunas_agrupadas[1:]

['CTMT', 'SIT_ATIV', 'POT_NOM', 'TIP_UNID_dic', 'TIP_UNID_detail_dic']

In [168]:
df_UNTRMT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count' }).reset_index()

,CTMT,SIT_ATIV,POT_NOM,TIP_UNID_dic,TIP_UNID_detail_dic,DIST
0,AGR008,AT,45.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,2
1,AGR008,AT,75.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,6
2,AGR008,AT,112.5,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,15
3,AGR008,AT,150.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,12
4,AGR008,AT,225.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,13
...,...,...,...,...,...,...
36,VRD014,AT,112.5,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,10
37,VRD014,AT,150.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,8
38,VRD014,AT,225.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,2
39,VRD014,AT,300.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,3
40,VRD014,AT,450.0,38_UNIDADE TRANSFORMADORA,38_TRANSFORMADOR DE DISTRIBUIÇÃO DE MÉDIA TENS...,4

### EQTR

In [169]:
EQTRMT = pd.read_pickle(path_info + eq[0] + ".pkl")
EQTRMT.columns

Index(['COD_ID', 'DIST', 'TIP_INST', 'UNI_TR_MT', 'CLAS_TEN', 'POT_NOM', 'LIG',
       'FAS_CON', 'TEN_PRI', 'TEN_SEC', 'TEN_TER', 'LIG_FAS_P', 'LIG_FAS_S',
       'LIG_FAS_T', 'ODI', 'TI', 'CM', 'TUC', 'A1', 'A2', 'A3', 'A4', 'A5',
       'A6', 'UAR', 'IDUC', 'SITCONT', 'DAT_IMO', 'PER_FER', 'PER_TOT', 'R',
       'XHL', 'XHT', 'XLT', 'DESCR', 'geometry', 'file', 'POT_NOM_dic',
       'TEN_PRI_dic', 'TEN_SEC_dic', 'TEN_TER_dic', 'TUC_dic', 'TUC_A1',
       'TUC_A1_dic', 'TUC_A2', 'TUC_A2_dic', 'TUC_A3', 'TUC_A3_dic', 'TUC_A4',
       'TUC_A4_dic', 'TUC_A5', 'TUC_A5_dic', 'TUC_A6', 'TUC_A6_dic'],
      dtype='object')

In [170]:

## Tucagem
colunas_agrupadas_eq = ['COD_ID','TIP_INST','POT_NOM_dic','UNI_TR_MT','TEN_PRI_dic','TEN_SEC_dic','TEN_TER_dic','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']

## Personalizado
# colunas_agrupadas_eq = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [171]:
colunas_agrupadas[1:]

['CTMT', 'SIT_ATIV', 'POT_NOM', 'TIP_UNID_dic', 'TIP_UNID_detail_dic']

In [172]:
agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_eq[1:]}

# Realize o merge e, em seguida, agrupe e aplique as agregações
sum_EQTRMT_MT = df_UNTRMT.merge(EQTRMT[colunas_agrupadas_eq], left_on='COD_ID', right_on=un[1], how='left') \
    .groupby(colunas_agrupadas[1:]) \
    .agg({**agg_dict, 'DIST': 'count'}) \
    .reset_index()

sum_EQTRMT_MT['nivel_tbl'] = 'MT'
sum_EQTRMT_MT.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# sum_EQTRMT_MT['Ativo'] = 'TRANSFORMADOR'
sum_EQTRMT_MT.head().style

In [173]:
sum_EQTRMT_MT.to_csv(path_res + 'res_TRMT.csv', sep=';', encoding='latin1', errors='ignore')

### SEBT

In [174]:
#trMT


un =  ["UNSEBT", "UN_SE"]
eq = ["EQSE"]

In [175]:
UNSEBT =   pd.read_pickle(path_info + un[0] + ".pkl")
UNSEBT.columns

Index(['COD_ID', 'DIST', 'PAC_1', 'PAC_2', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID',
       'P_N_OPE', 'CAP_ELO', 'COR_NOM', 'TLCD', 'DAT_CON', 'POS', 'UNI_TR_MT',
       'CTMT', 'UNI_TR_AT', 'SUB', 'CONJ', 'MUN', 'ARE_LOC', 'DESCR',
       'geometry', 'file', 'TIP_UNID_dic', 'TIP_UNID_detail_dic'],
      dtype='object')

In [176]:
df_UNSEBT = UNSEBT[UNSEBT['CTMT'].isin(alimentador['COD_ID'])]

In [177]:
# colunas_agrupadas = ['CTMT','DIST']
# colunas_agrupadas = ['DIST','CTMT', 'FAS_CON']
colunas_agrupadas = ['DIST','CTMT', 'FAS_CON', 'SIT_ATIV','TIP_UNID_dic', 'TIP_UNID_detail_dic', ]
# colunas_agrupadas = ['DIST','CTMT', 'TIP_REGU']
# colunas_agrupadas = ['DIST','CTMT', 'TIP_CND','TIP_INST', 'FAS_CON']

In [178]:
colunas_agrupadas[1:]

['CTMT', 'FAS_CON', 'SIT_ATIV', 'TIP_UNID_dic', 'TIP_UNID_detail_dic']

In [179]:
df_UNSEBT.groupby(colunas_agrupadas[1:]).agg({'DIST': 'count' }).reset_index()

,CTMT,FAS_CON,SIT_ATIV,TIP_UNID_dic,TIP_UNID_detail_dic,DIST
0,TQR60111,ABCN,AT,46_UNIDADE SECCIONADORA,46_FUSÍVEL,39
1,VRD014,ABCN,AT,46_UNIDADE SECCIONADORA,46_FUSÍVEL,4

### EQSE

In [180]:
EQSE.columns

Index(['COD_ID', 'DIST', 'TIP_INST', 'UN_SE', 'CLAS_TEN', 'ELO_FSV', 'MEI_ISO',
       'FAS_CON', 'COR_NOM', 'ODI', 'TI', 'CM', 'TUC', 'A1', 'A2', 'A3', 'A4',
       'A5', 'A6', 'UAR', 'IDUC', 'SITCONT', 'DAT_IMO', 'ABER_CRG', 'DESCR',
       'GRU_TEN', 'geometry', 'file', 'TUC_dic', 'TUC_A1', 'TUC_A1_dic',
       'TUC_A2', 'TUC_A2_dic', 'TUC_A3', 'TUC_A3_dic', 'TUC_A4', 'TUC_A4_dic',
       'TUC_A5', 'TUC_A5_dic', 'TUC_A6', 'TUC_A6_dic'],
      dtype='object')

In [181]:

## Tucagem
colunas_agrupadas_eq = ['COD_ID','TIP_INST','UN_SE','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']


## Personalizado
# colunas_agrupadas_eq = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [182]:
agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_eq[1:]}

# Realize o merge e, em seguida, agrupe e aplique as agregações
sum_EQSE_BT = df_UNSEBT.merge(EQSE[colunas_agrupadas_eq], left_on='COD_ID', right_on=un[1], how='left') \
    .groupby(colunas_agrupadas[1:]) \
    .agg({**agg_dict, 'DIST': 'count'}) \
    .reset_index()

sum_EQSE_BT['nivel_tbl'] = 'BT'
sum_EQSE_BT.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# sum_EQSE_BT['Ativo'] = 'TRANSFORMADOR'
sum_EQSE_BT.head().style

In [183]:
sum_EQSE_BT.to_csv(path_res + 'res_SEBT.csv', sep=';', encoding='latin1', errors='ignore')

### PONNOT

In [184]:
df_SSDBT_PN_1 = df_SSDBT[['CTMT', 'PN_CON_1']].rename(columns={'PN_CON_1': 'PN'})
df_SSDBT_PN_2 = df_SSDBT[['CTMT', 'PN_CON_2']].rename(columns={'PN_CON_2': 'PN'})
df_SSDMT_PN_1 = df_SSDMT[['CTMT', 'PN_CON_1']].rename(columns={'PN_CON_1': 'PN'})
df_SSDMT_PN_2 = df_SSDMT[['CTMT', 'PN_CON_2']].rename(columns={'PN_CON_2': 'PN'})
alimentador_pn = pd.concat([df_SSDBT_PN_1, df_SSDBT_PN_2,df_SSDMT_PN_1,df_SSDMT_PN_2]).drop_duplicates()
alimentador_pn

            CTMT         PN
230023    VRD014   55677930
230307    VRD014   55677937
230308    VRD014   55677944
230311    VRD014  240064824
231809    VRD014  277469217
...          ...        ...
889119  TQR60111   15698921
900860    SRP009  655290215
922602    VRD014  251122478
926348    VRD014  300043327
935611    PER763  156318877

[2359 rows x 2 columns]

In [4]:
PONNOT = pd.read_pickle(path_info + 'PONNOT.pkl')
PONNOT.columns

Index(['COD_ID', 'DIST', 'TIP_PN', 'TIP_INST', 'POS', 'ESTR', 'MAT', 'ESF',
       'ALT', 'ARE_LOC', 'CONJ', 'MUN', 'ODI', 'TI', 'CM', 'TUC', 'A1', 'A2',
       'A3', 'A4', 'A5', 'A6', 'UAR', 'SITCONT', 'DESCR', 'geometry', 'file',
       'TIP_PN_dic', 'ESTR_dic', 'MAT_dic', 'TUC_dic', 'TUC_A1', 'TUC_A1_dic',
       'TUC_A1_A2', 'TUC_A2_dic', 'TUC_A1_A3', 'TUC_A3_dic', 'TUC_A1_A4',
       'TUC_A4_dic', 'TUC_A1_A5', 'TUC_A5_dic', 'TUC_A1_A6', 'TUC_A6_dic'],
      dtype='object')

In [186]:

## Tucagem
colunas_agrupadas_pn = ['COD_ID','TIP_INST','TIP_PN_dic','ESTR_dic','MAT_dic','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']
colunas_agrupadas = ['CTMT']
## Personalizado
# colunas_agrupadas_pn = ['COD_ID','GEOM_CAB','GEOM_CAB_dsc','FORM_CAB', 'MAT_FAS_1','TUC_FAS', 'A1_FAS','A2_FAS']

In [187]:
(colunas_agrupadas_pn[1:])

['TIP_INST',
 'TIP_PN_dic',
 'ESTR_dic',
 'MAT_dic',
 'TUC_dic',
 'TUC_A1_dic',
 'TUC_A2_dic',
 'TUC_A3_dic',
 'TUC_A4_dic',
 'TUC_A5_dic',
 'TUC_A6_dic']

In [188]:
# agg_dict = {col: lambda x: ', '.join(x.astype(str)) for col in colunas_agrupadas_pn}

# # Realize o merge e, em seguida, agrupe e aplique as agregações
# sum_PN = alimentador_pn.merge(PONNOT, left_on='PN', right_on='COD_ID', how='left') \
#     .groupby(colunas_agrupadas) \
#     .agg({**agg_dict, 'DIST': 'count'}) \
#     .reset_index()

# # sum_EQSE_BT['nivel_tbl'] = 'BT'
# sum_PN.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
# # sum_EQSE_BT['Ativo'] = 'TRANSFORMADOR'
# sum_PN.head().style

In [189]:
colunas_agrupadas_pn = ['CTMT','TIP_INST','TIP_PN_dic','ESTR_dic','MAT_dic','TUC_dic', 'TUC_A1_dic','TUC_A2_dic','TUC_A3_dic', 'TUC_A4_dic', 'TUC_A5_dic', 'TUC_A6_dic']
colunas_agrupadas = ['CTMT']

In [190]:
sum_PN = alimentador_pn.merge(PONNOT, left_on = 'PN', right_on = 'COD_ID', how ='left').groupby(colunas_agrupadas_pn ).agg({'DIST': 'count'}).reset_index()#'len' : 'sum' }).reset_index()
sum_PN['Ativo'] = 'POSTE'
sum_PN.rename(columns={'DIST': 'QUANTIDADE'}, inplace=True)
sum_PN

,CTMT,TIP_INST,TIP_PN_dic,ESTR_dic,MAT_dic,TUC_dic,TUC_A1_dic,TUC_A2_dic,TUC_A3_dic,TUC_A4_dic,TUC_A5_dic,TUC_A6_dic,QUANTIDADE,Ativo
0,AGR008,LD_AER_AT,Poste,Duplo T,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.02_DUPLO T,255.01.01_CONCRETO,"255.01.10_10 m; 10,5 m",255.01.35_anterior até 1000 daN,255PST.00_N/A,1,POSTE
1,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.07_7 m; 7,5 m",255.01.10_anterior até 100 daN,255PST.00_N/A,2,POSTE
2,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.07_7 m; 7,5 m",255.01.16_anterior até 300 daN,255PST.00_N/A,4,POSTE
3,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.08_8 m; 8,5 m",255.01.16_anterior até 300 daN,255PST.00_N/A,2,POSTE
4,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.09_9 m,255.01.10_anterior até 100 daN,255PST.00_N/A,1,POSTE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.12_12 m,255.01.35_anterior até 1000 daN,255PST.00_N/A,7,POSTE
118,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.18_anterior até 400 daN,255PST.00_N/A,8,POSTE
119,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.20_anterior até 600 daN,255PST.00_N/A,3,POSTE
120,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.11_11 m,255.01.16_anterior até 300 daN,255PST.00_N/A,3,POSTE
121,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.12_12 m,255.01.20_anterior até 600 daN,255PST.00_N/A,1,POSTE

In [191]:
sum_PN.to_csv(path_res + 'res_PN.csv', sep=';', encoding='latin1', errors='ignore')

# Exportacao

In [196]:


# Iterar Sobre os circuitos
for ali in alimentador['COD_ID']:
    # Crie um novo arquivo Excel para cada circuito
    output_file = path_excel + ali + '.xlsx'
    workbook = xlsxwriter.Workbook(output_file)

    # Iterar sobre os DataFrames e salvar cada um em uma aba
    dataframes = {
        'SEGBT': sum_SEG_BT,
        'SEGMT': sum_SEG_MT,
        'CRMT': sum_EQCR_MT,
        'REMT': sum_EQRE_MT,
        'SEMT': sum_EQSE_MT,
        'TRMT': sum_EQTRMT_MT,
        'SEBT': sum_EQSE_BT,
        'PONNOT': sum_PN
    }

    for sheet_name, df in dataframes.items():
        # Crie uma nova aba no arquivo Excel
        worksheet = workbook.add_worksheet(sheet_name)

        df_sub = df[df['CTMT'] == ali]

        # Salve o DataFrame na aba
        for col_num, value in enumerate(df_sub.columns):
            worksheet.write(0, col_num, value)  # Escreva os cabeçalhos das colunas

        for row, data in enumerate(df_sub.values):
            worksheet.write_row(row + 1, 0, data)  # Comece a escrever os dados na segunda linha

    # Feche o arquivo Excel
    workbook.close()

In [197]:
df_sub

,CTMT,TIP_INST,TIP_PN_dic,ESTR_dic,MAT_dic,TUC_dic,TUC_A1_dic,TUC_A2_dic,TUC_A3_dic,TUC_A4_dic,TUC_A5_dic,TUC_A6_dic,QUANTIDADE,Ativo
102,VRD014,LD_AER_AT,Poste,Duplo T,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.02_DUPLO T,255.01.01_CONCRETO,"255.01.10_10 m; 10,5 m",255.01.35_anterior até 1000 daN,255PST.00_N/A,1,POSTE
103,VRD014,RD_AER_RUR,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.26_anterior até 800 daN,255PST.00_N/A,1,POSTE
104,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.09_9 m,255.01.16_anterior até 300 daN,255PST.00_N/A,27,POSTE
105,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.09_9 m,255.01.18_anterior até 400 daN,255PST.00_N/A,2,POSTE
106,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.10_10 m; 10,5 m",255.01.14_anterior até 200 daN,255PST.00_N/A,13,POSTE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.12_12 m,255.01.35_anterior até 1000 daN,255PST.00_N/A,7,POSTE
118,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.18_anterior até 400 daN,255PST.00_N/A,8,POSTE
119,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.20_anterior até 600 daN,255PST.00_N/A,3,POSTE
120,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.11_11 m,255.01.16_anterior até 300 daN,255PST.00_N/A,3,POSTE
121,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.12_12 m,255.01.20_anterior até 600 daN,255PST.00_N/A,1,POSTE

In [198]:
df

,CTMT,TIP_INST,TIP_PN_dic,ESTR_dic,MAT_dic,TUC_dic,TUC_A1_dic,TUC_A2_dic,TUC_A3_dic,TUC_A4_dic,TUC_A5_dic,TUC_A6_dic,QUANTIDADE,Ativo
0,AGR008,LD_AER_AT,Poste,Duplo T,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.02_DUPLO T,255.01.01_CONCRETO,"255.01.10_10 m; 10,5 m",255.01.35_anterior até 1000 daN,255PST.00_N/A,1,POSTE
1,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.07_7 m; 7,5 m",255.01.10_anterior até 100 daN,255PST.00_N/A,2,POSTE
2,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.07_7 m; 7,5 m",255.01.16_anterior até 300 daN,255PST.00_N/A,4,POSTE
3,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,"255.01.08_8 m; 8,5 m",255.01.16_anterior até 300 daN,255PST.00_N/A,2,POSTE
4,AGR008,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.09_9 m,255.01.10_anterior até 100 daN,255PST.00_N/A,1,POSTE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.12_12 m,255.01.35_anterior até 1000 daN,255PST.00_N/A,7,POSTE
118,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.18_anterior até 400 daN,255PST.00_N/A,8,POSTE
119,VRD014,RD_AER_URB,Poste,Circular,Concreto,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.01_CONCRETO,255.01.14_14 m,255.01.20_anterior até 600 daN,255PST.00_N/A,3,POSTE
120,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.11_11 m,255.01.16_anterior até 300 daN,255PST.00_N/A,3,POSTE
121,VRD014,RD_AER_URB,Poste,Circular,Madeira,"255_ESTRUTURA (POSTE, TORRE)",255.01_POSTE,255.01.01_CIRCULAR,255.01.02_MADEIRA,255.01.12_12 m,255.01.20_anterior até 600 daN,255PST.00_N/A,1,POSTE

In [199]:
ali

'VRD014'